steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.prod', '-t', 'us-east1-docker.pkg.dev/this-is-paradise/paradise/paradise:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east1-docker.pkg.dev/this-is-paradise/paradise/paradise:latest']